// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkMWmoh_BWJOt0l7SC5eYjnpm_bXIiNmI',
    appId: '1:290516968096:web:c2d40335d045cb95105fc5',
    messagingSenderId: '290516968096',
    projectId: 'pharmaaid-gaza',
    authDomain: 'pharmaaid-gaza.firebaseapp.com',
    storageBucket: 'pharmaaid-gaza.firebasestorage.app',
    measurementId: 'G-ZMJ49EDDCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTaCT-NYgb5_TMdrXe5-Eu5LmzCo3Sfq8',
    appId: '1:290516968096:android:5f511285a9f9143b105fc5',
    messagingSenderId: '290516968096',
    projectId: 'pharmaaid-gaza',
    storageBucket: 'pharmaaid-gaza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnAlQuPRW6mozjrN7nJpLiAksdu2ROLok',
    appId: '1:290516968096:ios:1a5022afa5af222c105fc5',
    messagingSenderId: '290516968096',
    projectId: 'pharmaaid-gaza',
    storageBucket: 'pharmaaid-gaza.firebasestorage.app',
    iosClientId: '290516968096-q7mutcq0da057jipdlvin5pl5tbo6ijo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmaaidGaza',
  );
}
